### ISSUE TITLE
Setup fails on HA Core 2026.4.1: TypeError via_device_id in async_get_or_create

### ISSUE THREAD

**Issue by dialink-lab** [HAEdwin/homeassistant-apsystems_ecu_reader#160]
## Requirements for submitting a bug
Help us by sharing us the relevant home-assistant.log part.
But before submitting, read this important info: https://github.com/HAEdwin/homeassistant-apsystems_ecu_reader/wiki/Debug-Mode-Guide
```
If relevant, paste the log in here
```

## Expected Behavior
Tell us what should happen

## Current Behavior
Tell us what happens instead of the expected behavior.

## Possible Solution
Not obligatory, but suggest a fix/reason for the bug

## Steps to Reproduce
Provide an unambiguous set of steps to reproduce this bug. 
  Include code or logging to reproduce, enable debug logging if relevant.
```
If relevant when reproducing the bug, paste the log in here
```

1.
2.
3.
4.

### Version
Integration: 2.15.0
Home Assistant Core: 2026.4.1
Installation: HA Container (Docker) on Raspberry Pi 5
ECU: ECU-R (216300143675), 1 × DS3 inverter

### Problem
After updating to 2.15.0 the config entry fails to set up.
`DeviceRegistry.async_get_or_create()` no longer accepts `via_device_id`;
HA Core expects `via_device` with the parent device's identifier tuple.

### Traceback
File "/config/custom_components/apsystems_ecu_reader/init.py", line 202, in async_setup_entry
device_registry.async_get_or_create(
config_entry_id=config.entry_id,
...
via_device_id=ecu_device.id,
)
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'via_device_id'. Did you mean 'via_device'?

### Fix that works for me
In `__init__.py`, inverter device registration:

```python
-            via_device_id=ecu_device.id,
+            via_device=(DOMAIN, f"ecu_{ecu.ecu.ecu_id}"),
```

The ECU device is registered a few lines above with
`identifiers={(DOMAIN, f"ecu_{ecu.ecu.ecu_id}")}`, so the tuple matches.
Setup completes and all 17 entities are back.

## Home Assistant hardware

- [X ] Raspberry Pi
- [X ] Docker container
- [ ] Virtual Machine
- [ ] Other

## PV-hardware
Providing context helps us come up with a solution that is most useful in the real world

- [X ] ECU-B
- [ ] ECU-R (2160 series)
- [ ] ECU-R-Pro (2162 series)
- [ ] ECU-C
- [ ] ECU-3

## ECU is connected by
- [ ] Ethernet cable
- [X ] Wireless

## Inverter type(s) used
- [X ] DS3 series
- [ ] QS series
- [ ] QT series
- [ ] YC series

```
APsystems ECU Reader software version and ECU firmware version currently installed
```

**Comment by HAEdwin** [comment]
Please read the release notes (https://github.com/HAEdwin/homeassistant-apsystems_ecu_reader/releases/tag/2.15.0), best you can do is roll-back to 2.14.0 or update Home Assistant.

**Comment by Lr972** [comment]
Hello Edwin,

Can confirm the same issue here, on a different ECU-C model 

Integration: 2.15.0
Home Assistant Core: 2026.7.2
Installation: HA OS in a Proxmox VM

Traceback (identical to the one above) : 

Logger: homeassistant.config_entries
Source: config_entries.py:798
Première occurrence: 22:11:58 (1 occurrence)
Dernier enregistrement: 22:11:58

Error setting up entry APsystems ECU 215000091859 for apsystems_ecu_reader
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/apsystems_ecu_reader/__init__.py", line 202, in async_setup_entry
    device_registry.async_get_or_create(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        config_entry_id=config.entry_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        via_device_id=ecu_device.id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'via_device_id'. Did you mean 'via_device'?

Thanks for all and Best Regards

Laurent

**Comment by HAEdwin** [comment]
See my comments above, best you can do is update to at least 2026.8.x or roll back to version 2.14.0

**Comment by Lr972** [comment]
I checked, but 2026.8.x isn't offered as an update on my instance yet (HA reports "No update available" on 2026.7.2). I'd rather not force a jump to 2026.8 blindly given some mixed reports on that release. 

Yes I have applied the rollback to 2.14.0, and it's Ok since one day. I posted my message just in case you decide to fix the issue.

Thanks for your attention and Best regards

Laurent.
